# Dockerfile.arm64
ARG ROS_DISTRO=jazzy
FROM arm64v8/ros:$ROS_DISTRO AS builder

WORKDIR /root/ws

RUN if id -u 1000; then userdel `id -un 1000` ; fi

RUN apt-get update && apt-get upgrade -y \
    && apt-get install -y \
    git \
    build-essential \
    python3-pip \
    python3-rosdep \
    python3-colcon-common-extensions \
    python3-serial \
    python3-yaml \
    ros-$ROS_DISTRO-rviz2 \
    ros-$ROS_DISTRO-dynamixel-sdk

RUN mkdir -p src

COPY src src

RUN . /opt/ros/$ROS_DISTRO/setup.sh && \
    colcon build --packages-select gar_interfaces gar_gauge_control

RUN tar -czf install.tar.gz install

# Export only the install folder
FROM scratch

COPY --from=builder root/ws/install.tar.gz /